const $=id=>document.getElementById(id);let b=[],o=[],charts={};const N=x=>Number(x)||0,money=n=>new Intl.NumberFormat('vi-VN',{notation:'compact',maximumFractionDigits:1}).format(N(n))+' ₫';
async function load(){let r=await fetch(APP_CONFIG.API_URL||APP_CONFIG.DEMO_DATA_URL),j=await r.json();b=j.bridge||[];o=j.opportunities||[];fill();render();$('source').textContent=APP_CONFIG.API_URL?'Nguồn: Google Sheets':'Đang dùng dữ liệu demo hợp nhất.'}
function fill(){[['month','Tháng'],['spdv','SPDV'],['area','Địa bàn'],['unit','Đơn vị']].forEach(([id,k])=>{let e=$(id),h=e.options[0].outerHTML;e.innerHTML=h;[...new Set(b.map(x=>x[k]).filter(v=>v!==''&&v!=null))].sort((a,b)=>a-b).forEach(v=>e.add(new Option(id==='month'?'Tháng '+v:v,v)))})}
function ok(x){return(!$('month').value||String(x['Tháng'])===$('month').value)&&(!$('spdv').value||x.SPDV===$('spdv').value)&&(!$('area').value||x['Địa bàn']===$('area').value)&&(!$('unit').value||x['Đơn vị']===$('unit').value)}
function sum(a,k){return a.reduce((s,x)=>s+N(x[k]),0)}function mk(id,type,labels,sets){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels,datasets:sets},options:{responsive:true,plugins:{legend:{display:true}},scales:type==='bar'||type==='line'?{y:{beginAtZero:true}}:{}}})}
function render(){let a=b.filter(ok),p=sum(a,'Kế hoạch'),ac=sum(a,'Thực hiện'),fc=sum(a,'Forecast SXKD'),wp=sum(a,'Weighted Pipeline'),short=Math.max(0,p-fc),cov=short?wp/short:999;
$('plan').textContent=money(p);$('actual').textContent=money(ac);$('rate').textContent=(p?ac/p*100:0).toFixed(1)+'% KH';$('forecast').textContent=money(fc);$('gap').textContent=(fc-p>=0?'+':'')+money(fc-p);$('gap').className=fc>=p?'green':'red';$('weighted').textContent=money(wp);$('coverage').textContent=short?cov.toFixed(1)+'x':'Không thiếu KH';
let months=[...new Set(a.map(x=>x['Tháng']))].sort((x,y)=>x-y),series=k=>months.map(m=>sum(a.filter(x=>x['Tháng']==m),k));mk('trend','line',months.map(x=>'T'+x),[{label:'KH',data:series('Kế hoạch')},{label:'TH',data:series('Thực hiện')},{label:'Forecast',data:series('Forecast SXKD')}]);
let ss=[...new Set(a.map(x=>x.SPDV))],gaps=ss.map(s=>Math.max(0,sum(a.filter(x=>x.SPDV===s),'Kế hoạch')-sum(a.filter(x=>x.SPDV===s),'Forecast SXKD'))),wps=ss.map(s=>sum(a.filter(x=>x.SPDV===s),'Weighted Pipeline'));mk('coverageChart','bar',ss,[{label:'Phần thiếu KH',data:gaps},{label:'Weighted Pipeline',data:wps}]);
let ids=new Set(a.flatMap(x=>[]));let opp=o.filter(x=>(!$('month').value||String(x['Tháng dự kiến chốt'])===$('month').value)&&(!$('spdv').value||x.SPDV===$('spdv').value)&&(!$('area').value||x['Địa bàn']===$('area').value)&&(!$('unit').value||x['Đơn vị']===$('unit').value));
let st={};opp.forEach(x=>st[x['Giai đoạn']]=(st[x['Giai đoạn']]||0)+N(x['Weighted Pipeline']));mk('stage','doughnut',Object.keys(st),[{label:'Weighted Pipeline',data:Object.values(st)}]);
let ow={};opp.filter(x=>N(x['Số tuần đứng yên'])>=2).forEach(x=>ow[x.Owner]=(ow[x.Owner]||0)+N(x['Weighted Pipeline']));mk('owner','bar',Object.keys(ow),[{label:'Pipeline đứng yên',data:Object.values(ow)}]);
let danger=[...a].sort((x,y)=>N(x['Coverage Gap'])-N(y['Coverage Gap'])||(N(x['Forecast SXKD'])-N(x['Kế hoạch']))-(N(y['Forecast SXKD'])-N(y['Kế hoạch']))).slice(0,20);
$('rows').innerHTML=danger.map(x=>`<tr><td>${x['Tháng']}</td><td>${x.SPDV}</td><td>${x['Địa bàn']}</td><td>${x['Đơn vị']}</td><td class="${N(x['Gap Forecast/KH'])<0?'red':'green'}">${money(N(x['Gap Forecast/KH']))}</td><td>${money(x['Weighted Pipeline'])}</td><td>${N(x['Coverage Gap'])>100?'—':N(x['Coverage Gap']).toFixed(1)+'x'}</td><td>${x['Số CHKD']}</td><td>${x['CHKD đứng yên ≥2 tuần']}</td><td>${x['Cảnh báo điều hành']}</td></tr>`).join('');
$('oppRows').innerHTML=[...opp].sort((x,y)=>N(y['Weighted Pipeline'])-N(x['Weighted Pipeline'])||N(y['Số tuần đứng yên'])-N(x['Số tuần đứng yên'])).slice(0,20).map(x=>`<tr><td>${x['Mã CHKD']}</td><td>${x['Tên cơ hội']}</td><td>${x.SPDV}</td><td>${x.Owner}</td><td>${money(x['Giá trị cơ hội'])}</td><td>${Math.round(N(x['Xác suất'])*100)}%</td><td>${money(x['Weighted Pipeline'])}</td><td>T${x['Tháng dự kiến chốt']}</td><td>${x['Số tuần đứng yên']}</td><td>${x['Next action']}</td></tr>`).join('');
let deficit=a.filter(x=>N(x['Gap Forecast/KH'])<0),red=deficit.filter(x=>x['Cảnh báo điều hành']==='Đỏ'),stale=opp.filter(x=>N(x['Số tuần đứng yên'])>=2),staleVal=sum(stale,'Weighted Pipeline');
$('insights').innerHTML=[`Forecast đạt <b>${(p?fc/p*100:0).toFixed(1)%</b> kế hoạch; phần thiếu hiện tại <b>${money(short)}</b>.`,`Weighted Pipeline CHKD có thể bao phủ <b>${short?cov.toFixed(1)+' lần':'toàn bộ'}</b> phần thiếu forecast.`,`Có <b>${red.length}</b> lát cắt Tháng × SPDV × Địa bàn đang cảnh báo Đỏ.`,`Có <b>${stale.length}</b> CHKD đứng yên ≥2 tuần, weighted pipeline ${money(staleVal)}; đây là nguồn cần ưu tiên làm sạch và thúc đẩy.`].map(x=>`<li>${x}</li>`).join('')}
['month','spdv','area','unit'].forEach(id=>$(id).addEventListener('change',render));$('refresh').addEventListener('click',load);load();